#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Code Generator for ImageFree Self-Play.

Takes full proposals (caption, easy_question, easy_answer, hard_question, hard_answer)
generated by the Proposer and uses a VLM (text-only mode) to generate self-contained
Python matplotlib code that renders the described chart. The rendered image should be
sufficient to answer both the easy and hard questions.

Modeled on question_generate/question_generate.py but outputs code instead of questions.
"""

import vllm
from transformers import AutoTokenizer
import argparse
from typing import List
from vllm.outputs import RequestOutput
import sys
import os
import json
import regex as re

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

STORAGE_PATH = os.getenv("STORAGE_PATH")

# ----------------------------- Prompt ----------------------------- #
# Load codegen.jinja so inference uses the exact same prompt the model
# was RL-fine-tuned on.  The template expects a single variable
# ``content`` which is the proposal text (same format as prompt_text
# in the training parquet).

_JINJA_PATH = os.path.join(
    os.path.dirname(__file__), '..', 'format_prompt', 'codegen.jinja'
)

def _load_codegen_template() -> str:
    with open(_JINJA_PATH, 'r') as f:
        return f.read()

_CODEGEN_TEMPLATE: str = _load_codegen_template()


def _build_prompt_text(proposal: dict) -> str:
    """Build the ``prompt_text`` content in the same format used by
    codegen GRPO training (see codegen_train.sh inline python)."""
    vt = str(proposal.get('visual_type', 'matplotlib')).strip().lower()
    if vt not in ('matplotlib', 'plotly', 'pillow', 'svg'):
        vt = 'matplotlib'
    hard_q = proposal.get('hard_question', '') or 'N/A'
    hard_a = proposal.get('hard_answer', '') or 'N/A'
    return (
        f"Visual Type: {vt}\n\n"
        f"Chart Description:\n{proposal['caption']}\n\n"
        f"Easy Question: {proposal['easy_question']}\n"
        f"Easy Answer: {proposal['easy_answer']}\n\n"
        f"Hard Question: {hard_q}\n"
        f"Hard Answer: {hard_a}"
    )


def _render_codegen_jinja(content: str) -> str:
    """Render the codegen.jinja template with the given content,
    producing the full user-message the model was trained on."""
    return _CODEGEN_TEMPLATE.replace('{{ content | trim }}', content.strip())

# ----------------------------- Parsing ----------------------------- #

def extract_code_block(response: str, visual_type: str = "matplotlib") -> str:
    """Extract code/SVG from response based on visual_type."""
    if visual_type == "svg":
        match = re.search(r"```(?:svg)?\s*\n([\s\S]*?)```", response)
        if match:
            return match.group(1).strip()
        s = response.strip()
        if s.lstrip().startswith("<") or "<?xml" in s[:100] or "<svg" in s[:200].lower():
            return s
        return ""
    match = re.search(r"```(?:python)?\s*\n([\s\S]*?)```", response)
    if match:
        return match.group(1).strip()
    lines = response.strip().split('\n')
    if lines and (lines[0].startswith('import ') or lines[0].startswith('from ')):
        return response.strip()
    return ""


def main(args):
    tokenizer = AutoTokenizer.from_pretrained(args.model)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    if tokenizer.pad_token_id is None:
        tokenizer.pad_token_id = tokenizer.eos_token_id

    # Use lower gpu_memory_util and max_model_len so this works when GPUs have limited free
    # memory (e.g. right after proposal generation: only ~40 GiB free on 80GB). Override with env if needed.
    gpu_mem_util = float(os.environ.get("VLLM_GPU_MEM_UTIL", "0.5"))
    max_model_len = int(os.environ.get("VLLM_MAX_MODEL_LEN", "32768"))
    model = vllm.LLM(
        model=args.model,
        tokenizer=args.model,
        seed=int(args.suffix),
        gpu_memory_utilization=gpu_mem_util,
        max_model_len=max_model_len,
    )

    sample_params = vllm.SamplingParams(
        max_tokens=4096,
        temperature=0.7,
        top_p=0.95,
        n=1,
        stop_token_ids=[tokenizer.eos_token_id],
    )

    # Load proposals generated by the Proposer
    input_file = f"{STORAGE_PATH}/generated_proposals/{args.save_name}_{args.suffix}.json"
    print(f"[{args.suffix}] Loading proposals from: {input_file}")
    try:
        with open(input_file, "r") as f:
            proposals = json.load(f)
    except FileNotFoundError:
        print(f"[{args.suffix}] ERROR: Input file not found: {input_file}")
        return

    # Filter to valid proposals (ones with all required fields)
    valid_proposals = [p for p in proposals
                       if p.get("caption") and p.get("easy_question") and p.get("easy_answer")]
    print(f"[{args.suffix}] Found {len(valid_proposals)} valid proposals out of {len(proposals)} total.")

    # Build prompts using the same format as codegen GRPO training:
    #   prompt_text (same as training parquet) → codegen.jinja → user message
    prompts = []
    proposal_visual_types = []
    for proposal in valid_proposals:
        vt = str(proposal.get('visual_type', 'matplotlib')).strip().lower()
        if vt not in ('matplotlib', 'plotly', 'pillow', 'svg'):
            vt = 'matplotlib'
        proposal_visual_types.append(vt)

        prompt_text = _build_prompt_text(proposal)
        user_msg = _render_codegen_jinja(prompt_text)

        prompt = (
            f"<|im_start|>user\n{user_msg}<|im_end|>\n"
            "<|im_start|>assistant\n"
        )
        prompts.append(prompt)

    print(f"[{args.suffix}] Generating code for {len(prompts)} proposals...")

    completions: List[RequestOutput] = model.generate(prompts, sampling_params=sample_params)

    results = []
    for i, (completion, proposal, vt) in enumerate(zip(completions, valid_proposals, proposal_visual_types)):
        response = completion.outputs[0].text
        code = extract_code_block(response, visual_type=vt)

        results.append({
            "visual_type": vt,
            "caption": proposal["caption"],
            "easy_question": proposal["easy_question"],
            "easy_answer": proposal["easy_answer"],
            "hard_question": proposal.get("hard_question", ""),
            "hard_answer": proposal.get("hard_answer", ""),
            "generated_code": code,
            "raw_response": response,
        })

    # Save results
    output_file = f"{STORAGE_PATH}/generated_code/{args.save_name}_{args.suffix}.json"
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    with open(output_file, "w") as f:
        json.dump(results, f, indent=4)

    print(f"[{args.suffix}] Generated code for {len(results)} proposals, saved to {output_file}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate matplotlib code from chart proposals.")
    parser.add_argument("--model", type=str, default="Qwen/Qwen2.5-VL-3B-Instruct", help="Model name or path")
    parser.add_argument("--suffix", type=str, default="0", help="Suffix for file naming (usually GPU index)")
    parser.add_argument("--save_name", type=str, default="codegen", help="Base name for input/output files")
    args = parser.parse_args()

    main(args)
